version: "3.8"

services:
  db:
    container_name: db
    platform: linux/amd64
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cinema

  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ../backend
      dockerfile: ../cinema-dev-config/Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/usr/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HASH_SALT: ${HASH_SALT}
    networks:
      - cinema

  prisma-studio:
    container_name: prisma-studio
    image: node:16-alpine
    working_dir: /usr/app
    volumes:
      - ../backend:/usr/app
    command: sh -c "npx prisma studio --port 5555"
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - cinema

  admin:
    container_name: admin
    platform: linux/amd64
    build:
      context: ../admin
      dockerfile: ../cinema-dev-config/Dockerfile.admin
    ports:
      - "3000:3000"
    volumes:
      - ../admin:/usr/app
    environment:
      VITE_IS_DEV: ${VITE_IS_DEV}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    networks:
      - cinema

  client:
    container_name: client
    platform: linux/amd64
    build:
      context: ../client
      dockerfile: ../cinema-dev-config/Dockerfile.client
    ports:
      - "3002:3000"
    volumes:
      - ../client:/usr/app
    environment:
      NEXT_PUBLIC_IS_DEV: ${NEXT_PUBLIC_IS_DEV}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    networks:
      - cinema

networks:
  cinema:
volumes:
  db:
