version: "3.8"

services:
  # frontend:
  #   container_name: frontend
  #   platform: linux/amd64
  #   build:
  #     context: ../frontend
  #     dockerfile: ../cinema-dev-config/Dockerfile.frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ../frontend:/usr/app
  #   environment:
  #     API_TOKEN: ${API_TOKEN}
  #     API_URL: ${API_URL}
  #   networks:
  #     - cinema

  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ../backend
      dockerfile: ../cinema-dev-config/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/usr/app
    environment:
      DATABASE_URL: "postgresql://admin:admin@localhost:5432/db?schema=public"
    networks:
      - cinema

  db:
    platform: linux/amd64
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cinema

networks:
  cinema:
volumes:
  db:
