version: "3.8"

services:
  db:
    container_name: db
    platform: linux/amd64
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cinema

  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ../backend
      dockerfile: ../cinema-dev-config/Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/usr/app
      - backend-node_modules:/usr/app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HASH_SALT: ${HASH_SALT}
    networks:
      - cinema

  admin:
    container_name: admin
    platform: linux/amd64
    build:
      context: ../admin
      dockerfile: ../cinema-dev-config/Dockerfile.admin
    ports:
      - "3000:3000"
    volumes:
      - ../admin:/usr/app
      - admin-node_modules:/usr/app/node_modules
    environment:
      VITE_IS_DEV: ${VITE_IS_DEV}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    networks:
      - cinema

networks:
  cinema:
volumes:
  db:
  backend-node_modules:
  admin-node_modules:
